server:
  port: ${PORT:0}
  
spring:
  application:
    name: search-bank-entity-ws
  profiles:
    active: development
  config:
    import: configserver:http://localhost:8888 #URL para localizar el config server.