#número del puerto a través de una variable de ambiente del sistema
#o si no hay ninguno, se asignará un puerto aleatorio disponible.
server:
  port: ${PORT:0}

spring:
  application:
    name: profile-credit-card-ws
  profiles:
    active: development 
  config:
    import: configserver:http://localhost:8888 #URL para localizar el config server.

ws:
  api:
    uri: /profiles